python-pygobject, g-ir.inc: Inherit gnomebase instead of gnome
Fix QA Issues by inheriting gnomebase instead of the whole gnome
bbclass.  The latter inherits gconf, which causes unrecognized options
to be passed to the components' configure scripts. Add explicit
qemu-native dependency in g-ir-tools-host.

Fixes the following QA Issues found when run with Dizzy oe-core:
ERROR: QA Issue: python-pygobject: configure was passed unrecognised
  options: --disable-schemas-install [unknown-configure-option]
ERROR: QA Issue: python-pygobject-native: configure was passed
  unrecognised options: --disable-schemas-install
  [unknown-configure-option]
ERROR: QA Issue: libgirepository: configure was passed unrecognised
  options: --disable-schemas-install [unknown-configure-option]
ERROR: QA Issue: g-ir-tools-native: configure was passed unrecognised
  options: --disable-schemas-install [unknown-configure-option]
ERROR: QA Issue: g-ir-tools-host: configure was passed unrecognised
  options: --disable-schemas-install [unknown-configure-option]
ERROR: QA Issue: g-ir-core: configure was passed unrecognised options:
  --disable-schemas-install [unknown-configure-option]
Add qemu-native dependency because qemuwrapper-cross itself doesn't
pull qemu-native dependency and removing gnome.bbclass removed
gtk-icon-cache.bbclass as well and that removes this dependency:
g-ir-tools-host -> gtk-update-icon-cache-native -> gdk-pixbuf-native
-> qemu-native